version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "Password123"
      PGUSER: postgres
    command: "-c 'work_mem=16MB' -c 'maintenance_work_mem=128MB'"
    ports:
      - "5432:5432"
    volumes:
      - jail-blotter-data:/var/lib/postgresql/data

volumes:
  jail-blotter-data:
